[2024-05-21T18:08:44.982+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T18:08:45.160+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_polygon_etl_v02.create_country_table scheduled__2024-05-20T00:00:00+00:00 [queued]>
[2024-05-21T18:08:45.193+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_polygon_etl_v02.create_country_table scheduled__2024-05-20T00:00:00+00:00 [queued]>
[2024-05-21T18:08:45.193+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-21T18:08:45.240+0000] {taskinstance.py:2330} INFO - Executing <Task(MsSqlOperator): create_country_table> on 2024-05-20 00:00:00+00:00
[2024-05-21T18:08:45.262+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_polygon_etl_v02', 'create_country_table', 'scheduled__2024-05-20T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag_polygon_etl.py', '--cfg-path', '/tmp/tmp64ek1f6x']
[2024-05-21T18:08:45.266+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask create_country_table
[2024-05-21T18:08:45.282+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=695) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-21T18:08:45.284+0000] {standard_task_runner.py:63} INFO - Started process 700 to run task
[2024-05-21T18:08:45.405+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_polygon_etl_v02.create_country_table scheduled__2024-05-20T00:00:00+00:00 [running]> on host 46d6b7e1bb4c
[2024-05-21T18:08:45.928+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kazik' AIRFLOW_CTX_DAG_ID='dag_polygon_etl_v02' AIRFLOW_CTX_TASK_ID='create_country_table' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-20T00:00:00+00:00'
[2024-05-21T18:08:45.930+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T18:08:45.962+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE Country (
            country_id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
            name TEXT,
            continent TEXT
        );
        
[2024-05-21T18:08:45.985+0000] {base.py:84} INFO - Using connection ID 'mssql' for task execution.
[2024-05-21T18:08:45.997+0000] {base.py:84} INFO - Using connection ID 'mssql' for task execution.
[2024-05-21T18:08:46.021+0000] {sql.py:470} INFO - Running statement: 
        CREATE TABLE Country (
            country_id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
            name TEXT,
            continent TEXT
        );
        , parameters: None
[2024-05-21T18:08:46.026+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T18:08:46.027+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 447, in pymssql._pymssql.Cursor.execute
  File "src/pymssql/_mssql.pyx", line 1125, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1156, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1289, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src/pymssql/_mssql.pyx", line 1852, in pymssql._mssql.check_cancel_and_raise
  File "src/pymssql/_mssql.pyx", line 1898, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (2714, b"There is already an object named 'Country' in the database.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 418, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 475, in _run_command
    cur.execute(sql_statement)
  File "src/pymssql/_pymssql.pyx", line 465, in pymssql._pymssql.Cursor.execute
pymssql.exceptions.OperationalError: (2714, b"There is already an object named 'Country' in the database.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[2024-05-21T18:08:46.048+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_polygon_etl_v02, task_id=create_country_table, run_id=scheduled__2024-05-20T00:00:00+00:00, execution_date=20240520T000000, start_date=20240521T180845, end_date=20240521T180846
[2024-05-21T18:08:46.079+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task create_country_table ((2714, b"There is already an object named 'Country' in the database.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n"); 700)
[2024-05-21T18:08:46.121+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-21T18:08:46.197+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T18:08:46.205+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
